"""initial schema

Revision ID: 106fb09e230f
Revises: 
Create Date: 2026-08-29 13:41:01.817731

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '106fb09e230f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cnpj', sa.String(length=14), nullable=False),
    sa.Column('razao_social', sa.String(length=255), nullable=False),
    sa.Column('nome_fantasia', sa.String(length=255), nullable=True),
    sa.Column('situacao_cadastral', sa.String(length=50), nullable=False),
    sa.Column('situacao_cadastral_data', sa.Date(), nullable=True),
    sa.Column('data_abertura', sa.Date(), nullable=True),
    sa.Column('capital_social', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('natureza_juridica_codigo', sa.String(length=10), nullable=True),
    sa.Column('natureza_juridica_descricao', sa.String(length=255), nullable=True),
    sa.Column('porte', sa.String(length=50), nullable=True),
    sa.Column('cnae_principal_codigo', sa.String(length=10), nullable=True),
    sa.Column('cnae_principal_descricao', sa.String(length=255), nullable=True),
    sa.Column('logradouro', sa.String(length=255), nullable=True),
    sa.Column('numero', sa.String(length=20), nullable=True),
    sa.Column('complemento', sa.String(length=255), nullable=True),
    sa.Column('bairro', sa.String(length=255), nullable=True),
    sa.Column('municipio', sa.String(length=255), nullable=True),
    sa.Column('uf', sa.String(length=2), nullable=True),
    sa.Column('cep', sa.String(length=8), nullable=True),
    sa.Column('address_key', sa.String(length=40), nullable=True),
    sa.Column('source_provider', sa.String(length=20), nullable=False),
    sa.Column('source_collected_at', sa.DateTime(), nullable=False),
    sa.Column('raw_response', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_companies_address_key'), 'companies', ['address_key'], unique=False)
    op.create_index(op.f('ix_companies_cnpj'), 'companies', ['cnpj'], unique=True)
    op.create_table('dossier_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('root_cnpj', sa.String(length=14), nullable=False),
    sa.Column('expected_activity_description', sa.String(), nullable=True),
    sa.Column('graph_depth', sa.Integer(), nullable=False),
    sa.Column('requested_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dossier_requests_root_cnpj'), 'dossier_requests', ['root_cnpj'], unique=False)
    op.create_table('people',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cpf_masked', sa.String(length=20), nullable=True),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('faixa_etaria', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf_masked', 'nome', name='uq_people_cpf_masked_nome')
    )
    op.create_table('cnae_secundarios',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('codigo', sa.String(length=10), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('company_partnerships',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('subject_company_id', sa.UUID(), nullable=False),
    sa.Column('object_company_id', sa.UUID(), nullable=False),
    sa.Column('qualificacao', sa.String(length=255), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['object_company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('partnerships',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('person_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('qualificacao', sa.String(length=255), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('partnerships')
    op.drop_table('company_partnerships')
    op.drop_table('cnae_secundarios')
    op.drop_table('people')
    op.drop_index(op.f('ix_dossier_requests_root_cnpj'), table_name='dossier_requests')
    op.drop_table('dossier_requests')
    op.drop_index(op.f('ix_companies_cnpj'), table_name='companies')
    op.drop_index(op.f('ix_companies_address_key'), table_name='companies')
    op.drop_table('companies')
    # ### end Alembic commands ###
