"""add batch checks

Revision ID: 1fa1e9cb9f5b
Revises: 0820ea4a1b18
Create Date: 2026-09-24 17:22:47.053498

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1fa1e9cb9f5b'
down_revision: Union[str, Sequence[str], None] = '0820ea4a1b18'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('batch_checks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_batch_checks_created_at'), 'batch_checks', ['created_at'], unique=False)
    op.create_index(op.f('ix_batch_checks_user_id'), 'batch_checks', ['user_id'], unique=False)
    op.create_table('batch_check_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('batch_id', sa.UUID(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('cnpj', sa.String(length=14), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('razao_social', sa.String(length=255), nullable=True),
    sa.Column('situacao_cadastral', sa.String(length=50), nullable=True),
    sa.Column('flags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['batch_checks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_batch_check_items_batch_id'), 'batch_check_items', ['batch_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_batch_check_items_batch_id'), table_name='batch_check_items')
    op.drop_table('batch_check_items')
    op.drop_index(op.f('ix_batch_checks_user_id'), table_name='batch_checks')
    op.drop_index(op.f('ix_batch_checks_created_at'), table_name='batch_checks')
    op.drop_table('batch_checks')
    # ### end Alembic commands ###
