"""add people.graph_ref_id

Revision ID: 53c2fdedf34a
Revises: 106fb09e230f
Create Date: 2026-08-29 13:55:12.019035

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53c2fdedf34a'
down_revision: Union[str, Sequence[str], None] = '106fb09e230f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('people', sa.Column('graph_ref_id', sa.String(length=64), nullable=True))
    op.create_unique_constraint(None, 'people', ['graph_ref_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'people', type_='unique')
    op.drop_column('people', 'graph_ref_id')
    # ### end Alembic commands ###
