"""add restrictive_list_entries

Revision ID: 6743269632f8
Revises: 53c2fdedf34a
Create Date: 2026-08-29 15:53:35.830105

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6743269632f8'
down_revision: Union[str, Sequence[str], None] = '53c2fdedf34a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('restrictive_list_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('list_type', sa.String(length=20), nullable=False),
    sa.Column('external_id', sa.String(length=100), nullable=False),
    sa.Column('document', sa.String(length=14), nullable=False),
    sa.Column('document_type', sa.String(length=4), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=True),
    sa.Column('source_org', sa.String(length=255), nullable=True),
    sa.Column('sanction_start_date', sa.Date(), nullable=True),
    sa.Column('sanction_end_date', sa.Date(), nullable=True),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('ingested_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('list_type', 'external_id', name='uq_restrictive_list_entry_source')
    )
    op.create_index(op.f('ix_restrictive_list_entries_document'), 'restrictive_list_entries', ['document'], unique=False)
    op.create_index(op.f('ix_restrictive_list_entries_list_type'), 'restrictive_list_entries', ['list_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_restrictive_list_entries_list_type'), table_name='restrictive_list_entries')
    op.drop_index(op.f('ix_restrictive_list_entries_document'), table_name='restrictive_list_entries')
    op.drop_table('restrictive_list_entries')
    # ### end Alembic commands ###
