"""add federal debts

Revision ID: efaca37366df
Revises: 1fa1e9cb9f5b
Create Date: 2026-09-24 17:29:38.592904

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'efaca37366df'
down_revision: Union[str, Sequence[str], None] = '1fa1e9cb9f5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('federal_debts',
    sa.Column('cnpj_root', sa.String(length=8), nullable=False),
    sa.Column('amount_cents', sa.BigInteger(), nullable=False),
    sa.Column('inscriptions', sa.Integer(), nullable=False),
    sa.Column('judicial', sa.Boolean(), nullable=False),
    sa.Column('reference', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('cnpj_root')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('federal_debts')
    # ### end Alembic commands ###
